### ISSUE TITLE
Project proposal - Draft version

### ISSUE THREAD

**Issue by ShuzhiZhong** [msep2019/MSEP_2019_3#3]
- [ ] Abstract #4 
- [ ] Proposal - Introduction + Motivation + Novelty Statement #5 
- [ ] Proposal - Background + Related Work #6 
- [ ] Proposal - Studied Subjects/Datasets #7 
- [ ] Proposal - Details of Expected Deliverables #8 
- [ ] Proposal - Gantt Chart + Individual contributions #9 
- [ ] References
